http:
  routers:
    gridops:
      rule: "Host(`ops.antonlabs.cc`)"
      entryPoints:
        - websecure
      service: gridops
      tls: {}

  services:
    gridops:
      loadBalancer:
        servers:
          - url: "http://gridops-api:8080"
